default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :coverage do
    gradle(task: "jacocoTestReport")
    sh("java -jar codacy-coverage-reporter-4.0.1-assembly.jar report -r firestorelivedata/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml -l Kotlin")
  end
end
